### ISSUE TITLE
Error when attempting to install using PackageControl

### ISSUE THREAD

**Issue by OmarArain** [tuteken/Keypirinha-Plugin-Pinboard#4]
I encountered the following error when attempting to install this package, using the PackageControl Plugin.

```text
23:41:05.818 ** ERROR: Error from Pinboard.Pinboard.on_catalog: <class 'TypeError'>: must be str, not NoneType
Traceback (most recent call last):
  File "C:\Program Files\Keypirinha\portable\Profile\InstalledPackages\Pinboard.keypirinha-package\pinboard.py", line 91, in on_catalog
  File "C:\Program Files\Keypirinha\portable\Profile\InstalledPackages\Pinboard.keypirinha-package\pinboard.py", line 235, in _download_bookmarks
```

**Comment by OmarArain** [comment]
I'm guessing this has to do with not having the API token, since my installation seems to have worked.

**Comment by tuteken** [comment]
Thank you for your interest in this project.  I have stopped using Keypirinha and will be archiving this repository.
